// export const DELETE_EVENT = 'DELETE_EVENT';
// export const DELETE_ALL_EVENTS = 'DELETE_ALL_EVENTS';
// export const CREATE_EVENT = 'CREATE_EVENT';
// export const ADD_OPERATION_LOG = 'ADD_OPERATION_LOG';
// export const DELETE_ALL_OPERATION_LOGS = 'DELETE_ALL_OPERATION_LOGS';

export const ActionTypes = {
  DELETE_EVENT :'DELETE_EVENT',
  DELETE_ALL_EVENTS : "DELETE_ALL_EVEMTS",
  CREATE_EVENT : "CREATE_EVENT",
  ADD_OPERATION_LOG : "ADD_OPERATION_LOG",
  DELETE_ALL_OPERATION_LOGS : "DELETE_ALL_OPERATION_LOGS",
}